llm:
  api_base: "http://127.0.0.1:8000/v1"
  model: "Models/Qwen2.5-72b-Instruct"
  api_key: "token-abc123"
  temperature: 0.0

embeddings:
  model: "custom-embedding-zh"
  base_url: "http://45.252.106.202:9997/v1"
  api_key: "not empty" 

prompts:
  retrieval_grader: |
    You are a grader assessing relevance of a retrieved document to a user question.
    It does not need to be a stringent test. The goal is to filter out erroneous retrievals.
    If the document contains keyword(s) or semantic meaning related to the user question, grade it as relevant.
    Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question.

  hallucination_grader: |
    You are a grader assessing whether an LLM generation is grounded in / supported by a set of retrieved facts.
    Give a binary score 'yes' or 'no'. 'Yes' means that the answer is grounded in / supported by the set of facts.

  answer_grader: |
    You are a grader assessing whether an answer addresses / resolves a question
    Give a binary score 'yes' or 'no'. Yes' means that the answer resolves the question.

  question_rewriter: |
    You a question re-writer that converts an input question to a better version that is optimized
    for vectorstore retrieval. Look at the input and try to reason about the underlying semantic intent / meaning.